### ISSUE TITLE
Incompatible with stimulus reflex 3.5.0.rc4

### ISSUE THREAD

**Issue by trnal** [joshleblanc/view_component_reflex#106]
Reflexes are not triggered on the components because the validation of the method name fails. 
`verify_method_name!`

https://github.com/stimulusreflex/stimulus_reflex/commit/538582d240439aab76066c72335ea92096cd0c7f

**Comment by joshleblanc** [comment]
I'll take a look at this tonight

**Comment by joshleblanc** [comment]
@trnal Give version 3.3.3 a try and let me know

**Comment by Laykou** [comment]
Using the latest 3.3.10 version it now fails on the issue that all methods created in `build_reflex_instance` have only `*args` and `&blk` as arguments.

StimulsReflex validates number of arguments here https://github.com/stimulusreflex/stimulus_reflex/blob/a0ef193c770d849856ebee420a7135f082a7c31c/app/channels/stimulus_reflex/channel.rb#L86

The `method.parameters` now always returns two parameters `[:args, :blk]` even if the original method has no arguments and there is mismatch `2 != 0` and therefore all such reflexes fail

**Comment by Laykou** [comment]
Thank you for a quick response. I tried with SR 3.3.3 as well as latest SR 3.5.5.

![Image](https://github.com/user-attachments/assets/e9891cbd-2668-47a6-953c-de98d25f02c8)

The error leads me here:

> wrong number of arguments (given [""], expected [], optional [])

![Image](https://github.com/user-attachments/assets/c7c34962-d7de-419e-8676-6649cc0299f2)

My method `def add_field` has no arguments, however as you can see here the `method.parameters` returns it has `*args` and `&blk` which comes from the dynamically defined_method.

StimulusReflex checks here in `delegate_call_to_reflex` number of arguments and eventually throws an error. My frontend didn't submitted any parameters, however the backend expected something.

Is the combination of view_component_reflex 3.3.10 and SR 3.3.5 working for you? Am I missing something?

**Comment by joshleblanc** [comment]
@Laykou  Not seeing it on my end, can you provide the stack trace?

The `delegate_call_to_reflex` method that's called within build_reflex_instance should be calling ViewComponentReflex::Reflex#delegate_call_to_reflex`, not StimulusReflex::Channel#delegate_call_to_reflex

The stack trace would help here, to know if we're calling the wrong method

**Comment by Laykou** [comment]
Here you are:

```
Reflex DynamicData::InputConditions::Component#add_field failed: wrong number of arguments (given [""], expected [], optional []) [http://factcool.test.flowis.com.localhost:3032/admin/workflows/workflows/new]
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/stimulus_reflex-3.5.5/app/channels/stimulus_reflex/channel.rb:91:in 'StimulusReflex::Channel#delegate_call_to_reflex'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/stimulus_reflex-3.5.5/app/channels/stimulus_reflex/channel.rb:16:in 'StimulusReflex::Channel#receive'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/view_component_reflex-3.3.10/lib/view_component_reflex/engine.rb:30:in 'StimulusReflex::Channel#receive'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/channel/base.rb:284:in 'Kernel#public_send'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/channel/base.rb:284:in 'ActionCable::Channel::Base#dispatch_action'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/sentry-rails-5.21.0/lib/sentry/rails/action_cable.rb:100:in 'block in Sentry::Rails::ActionCableExtensions::Channel::Actions#dispatch_action'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/sentry-rails-5.21.0/lib/sentry/rails/action_cable.rb:26:in 'block in Sentry::Rails::ActionCableExtensions::ErrorHandler.capture'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/sentry-ruby-5.21.0/lib/sentry/hub.rb:59:in 'Sentry::Hub#with_scope'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/sentry-ruby-5.21.0/lib/sentry-ruby.rb:392:in 'Sentry.with_scope'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/sentry-rails-5.21.0/lib/sentry/rails/action_cable.rb:18:in 'Sentry::Rails::ActionCableExtensions::ErrorHandler.capture'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/sentry-rails-5.21.0/lib/sentry/rails/action_cable.rb:99:in 'Sentry::Rails::ActionCableExtensions::Channel::Actions#dispatch_action'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/channel/base.rb:181:in 'block in ActionCable::Channel::Base#perform_action'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/notifications.rb:210:in 'block in ActiveSupport::Notifications.instrument'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/notifications/instrumenter.rb:58:in 'ActiveSupport::Notifications::Instrumenter#instrument'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/notifications.rb:210:in 'ActiveSupport::Notifications.instrument'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/channel/base.rb:180:in 'ActionCable::Channel::Base#perform_action'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/connection/subscriptions.rb:61:in 'ActionCable::Connection::Subscriptions#perform_action'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/connection/subscriptions.rb:24:in 'ActionCable::Connection::Subscriptions#execute_command'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/anycable-rails-core-1.5.6/lib/anycable/rails/ext/whisper.rb:24:in 'execute_command'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/connection/base.rb:111:in 'block in ActionCable::Connection::Base#handle_channel_command'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/callbacks.rb:120:in 'block in ActiveSupport::Callbacks#run_callbacks'
/Users/laykou/Projects/flowis/app/channels/application_cable/connection.rb:40:in 'block in ApplicationCable::Connection#set_schema_tenant'
/Users/laykou/Projects/flowis/lib/schema_tenant.rb:24:in 'SchemaTenant.switch'
/Users/laykou/Projects/flowis/app/channels/application_cable/connection.rb:31:in 'ApplicationCable::Connection#set_schema_tenant'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/callbacks.rb:129:in 'block in ActiveSupport::Callbacks#run_callbacks'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/callbacks.rb:140:in 'ActiveSupport::Callbacks#run_callbacks'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/connection/base.rb:110:in 'ActionCable::Connection::Base#handle_channel_command'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/connection/base.rb:103:in 'ActionCable::Connection::Base#dispatch_websocket_message'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/server/worker.rb:60:in 'block in ActionCable::Server::Worker#invoke'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/callbacks.rb:120:in 'block in ActiveSupport::Callbacks#run_callbacks'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/tagged_logging.rb:143:in 'block in ActiveSupport::TaggedLogging#tagged'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/tagged_logging.rb:38:in 'ActiveSupport::TaggedLogging::Formatter#tagged'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/tagged_logging.rb:143:in 'ActiveSupport::TaggedLogging#tagged'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/broadcast_logger.rb:241:in 'ActiveSupport::BroadcastLogger#method_missing'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/connection/tagged_logger_proxy.rb:29:in 'ActionCable::Connection::TaggedLoggerProxy#tag'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/server/worker/active_record_connection_management.rb:18:in 'ActionCable::Server::Worker::ActiveRecordConnectionManagement#with_database_connections'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/callbacks.rb:129:in 'block in ActiveSupport::Callbacks#run_callbacks'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/engine.rb:81:in 'block (4 levels) in <class:Engine>'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/execution_wrapper.rb:91:in 'ActiveSupport::ExecutionWrapper.wrap'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/engine.rb:76:in 'block (3 levels) in <class:Engine>'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/callbacks.rb:129:in 'BasicObject#instance_exec'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/callbacks.rb:129:in 'block in ActiveSupport::Callbacks#run_callbacks'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/activesupport-8.0.2/lib/active_support/callbacks.rb:140:in 'ActiveSupport::Callbacks#run_callbacks'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/server/worker.rb:43:in 'ActionCable::Server::Worker#work'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/server/worker.rb:59:in 'ActionCable::Server::Worker#invoke'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/actioncable-8.0.2/lib/action_cable/server/worker.rb:54:in 'block in ActionCable::Server::Worker#async_invoke'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in 'Concurrent::RubyThreadPoolExecutor::Worker#run_task'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in 'block (3 levels) in Concurrent::RubyThreadPoolExecutor::Worker#create_worker'
<internal:kernel>:168:in 'Kernel#loop'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in 'block (2 levels) in Concurrent::RubyThreadPoolExecutor::Worker#create_worker'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in 'Kernel#catch'
/Users/laykou/.rvm/gems/ruby-3.4.4/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in 'block in Concurrent::RubyThreadPoolExecutor::Worker#create_worker'
```

**Comment by Laykou** [comment]
Let me update how the call is made. This code is simplified:

```html
<div data-controller="my-controller">
  <select data-action="change->my-controller#addField" reflex_dataset="ancestors [data-xxx-state]"></select>
</div>
```

```js
import { Controller } from '@hotwired/stimulus';

export class Controller extends Controller {
  connect() {
    StimulusReflex.register(this);
  }

  addField(event) {
    let serializedInputConditions = this.serializeInputConditions(event);

    this.stimulate('InputConditions::Component#add_field', event.target, { serializeForm: false }, serializedInputConditions);
  }

  serializeInputConditions(event) {
    return ''; // The logic here is ommited. This can return also an empty string
  }
}
```

```ruby
module InputConditions
  class Component < ViewComponentReflex::Component
    def add_field(input_conditions)
      # Do something
    end
  end
end
```

**Comment by joshleblanc** [comment]
@Laykou 

Earlier, you said `add_field` was defined to take no arguments. Your code example here has it accepting one argument.

I'm just trying to reproduce the problem on my end - can you clarify if the method has one or no arguments?

**Comment by Laykou** [comment]
It has one argument, previously I was mistaken. Nevertheless the issue is still the same:

- reflex is received with `['']` - one argument representing an empty string
- the `def add_field` is evaluated as having `[[:rest, :args], [:block, :blk]]` parameters and none of them (0) are required

The `(input_conditions)` argument is not captured here

Therfore an argument mismatch is raised

**Comment by Laykou** [comment]
@joshleblanc What I'm doing here is manually calling the ViewComponent's Reflex class from the JS (using `this.stimulate`).

I haven't found such example anywhere in the docs. Maybe this is not fully supported?

**Comment by joshleblanc** [comment]
@Laykou Can you try 3.3.11?

**Comment by Laykou** [comment]
@joshleblanc Now it works! Thank you. Let me run full end-to-end tests (Cypress) to see if we will find out another issue and I will close this ticket

**Comment by Laykou** [comment]
@joshleblanc Here I see the StimulusReflex is calling `reflex.id` method. This method is defined as `delegate :id, to: :reflex_data` on StimulusReflex class

<img width="917" height="233" alt="Image" src="https://github.com/user-attachments/assets/018106ec-294f-4252-a25a-7e71fa61afc7" />

I see the issue is that this call is going through `delegate_call_to_reflex`. The code then fails on inicialization of `controller` object which is needed for the `morph` method used in the `delegate_call_to_reflex`, however that's just the secondary problem. The primary problem is that the `.id` method is NOT a method that should be considered as a "reflex" method, right?


For some reason these attribute getters/setter  are part of the:

```
reflex_methods = @component.instance_methods - @component.superclass.instance_methods - [:call, :"_call_#{@component.name.underscore}"]
```

even though I think they should not appear in this array. Here we want only the custom methods defined directly on the ViewComponentReflex class by the developer, right?

**Comment by Laykou** [comment]
@joshleblanc Sorry to iterate over and over again, but I still see some flaws - this breaks inheritance of Components.

Let's say I have:

```ruby
class AbstractComponent < ApplicationViewComponent
  def my_method
  end
end

class MyComponent < AbstractComponent
end
```

I would assume calling reflex for `MyComponent#my_method` should work properly, however the `my_method` is not part of the `@component.instance_methods - @component.superclass.instance_methods` since appears only on the parent.

As a developer I would expect this to work - so that I can share the `my_method` as a reflex method across different components. This is right now not supported, right?

**Comment by joshleblanc** [comment]
@Laykou  I see what's going on with the inheritance. I use inheritance in this project, but everything still always calls it's own reflex methods through sheer happenstance.

I just pushed 3.3.12 that collects the methods from all superclasses. Let me know if that resolves your issue.

**Comment by Laykou** [comment]
I would say doing

```ruby
reflex_methods = @component.instance_methods - ViewComponentReflex::Component.instance_methods - [:call, :"_call_#{@component.name.underscore}"]
```

should be just fine. The `instance_methods` returns ALL superclass methods too unless it's provided with `false` argument `instance_methods(false)`.

So I assume you do not need to do any loop across parent classes. This fix looks good and I'm still analyzing some other issue

**Comment by Laykou** [comment]
I understand the fix here https://github.com/joshleblanc/view_component_reflex/commit/40b0879465f7f20cf27edcfe87b4a4a276fb6c5f however this broke the "inheritance" of callbacks. Take this example:

```ruby
class AbstractClass
  class << self
    def register_callback(val)
      @callback ||= []
      @callback << val
    end

    def callbacks
      puts @callback.inspect
    end
  end

  register_callback(1)
end

class MyClass < AbstractClass
  register_callback(2)
end

MyClass.callbacks
# -> [2]
```

The `MyClass` returns only `[2]` and the callback `1` is not registered.
So either there should be a known issue that callbacks are not inherited (which is usually supported in Rails, e.g. Controllers or standard StimulusReflex) or this somehow needs to be addressed too

**Comment by joshleblanc** [comment]
@Laykou I believe I introduced this when I moved from class variable to class instance variables for callbacks. I just pushed a new version that collects the callbacks from ancestors during registration. Let me know if it resolves the issue on your end.

**Comment by joshleblanc** [comment]
@Laykou What reflex method name are you hitting?

Breakpoint at reflex.rb#121

**Comment by joshleblanc** [comment]
@Laykou  Yeah, pushed a version. 

But if you're hitting that as a reflex action, you're likely going to just get another error that the reflex doesn't exist, unless I'm misunderstanding what's happening here.

**Comment by joshleblanc** [comment]
@Laykou  Yeah that makes a lot of sense. Let me see what I can do

**Comment by joshleblanc** [comment]
@Laykou That's up, thanks for the suggestion!

**Comment by Laykou** [comment]
Thank you, I suggest closing this since everything seems to be running fine for us in PROD for couple of months
